
package farmacia;
import java.awt.*;

public class CARTAS_VENCIMIENTO extends javax.swing.JPanel {

    /**
     * Creates new form Carta
     */
    
    public CARTAS_VENCIMIENTO(int codigo, String nombre, String ubicacion, String principio, String fechaVencimiento, int stock) {
        initComponents();
        this.lbcodigo.setText("CODIGO: "+ codigo);
        this.lbnombre.setText("NOMBRE: "+ nombre);
        this.lblaboratorio.setText("UBICACION: "+ ubicacion);
        this.lbprincipio.setText("PRINCIPIO ACTIVO: "+ principio);
        this.lbstock.setText("F. VEMCIMIENTO: "+ fechaVencimiento);
        this.lbubicacion.setText("STOCK: "+ stock);
        
       setPreferredSize(new Dimension(300, 240));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbcodigo = new javax.swing.JLabel();
        lbnombre = new javax.swing.JLabel();
        lblaboratorio = new javax.swing.JLabel();
        lbstock = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbprincipio = new javax.swing.JLabel();
        lbubicacion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(177, 212, 224), new java.awt.Color(177, 212, 224)));
        setPreferredSize(new java.awt.Dimension(300, 240));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alerta_de_usuario.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 70, 70));

        lbcodigo.setBackground(new java.awt.Color(0, 0, 0));
        lbcodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbcodigo.setForeground(new java.awt.Color(0, 0, 0));
        lbcodigo.setText("jLabel1");
        lbcodigo.setToolTipText("");
        add(lbcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, -1));

        lbnombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbnombre.setForeground(new java.awt.Color(0, 0, 0));
        lbnombre.setText("jLabel2");
        add(lbnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, -1));

        lblaboratorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblaboratorio.setForeground(new java.awt.Color(0, 0, 0));
        lblaboratorio.setText("jLabel2");
        add(lblaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 270, -1));

        lbstock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbstock.setForeground(new java.awt.Color(0, 0, 0));
        lbstock.setText("jLabel2");
        add(lbstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 270, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(177, 212, 224), new java.awt.Color(177, 212, 224)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        lbprincipio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbprincipio.setForeground(new java.awt.Color(0, 0, 0));
        lbprincipio.setText("jLabel2");
        add(lbprincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 270, -1));

        lbubicacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbubicacion.setForeground(new java.awt.Color(0, 0, 0));
        lbubicacion.setText("jLabel2");
        add(lbubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 270, -1));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JLabel lblaboratorio;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbprincipio;
    private javax.swing.JLabel lbstock;
    private javax.swing.JLabel lbubicacion;
    // End of variables declaration//GEN-END:variables
}
