/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package farmacia;

import Implementaciones.DAOUserImpl;
import db.conexion;
import interfaces.DAOProductos;
import java.util.logging.Level;
import java.util.logging.Logger;
import objetos.producto;

/**
 *
 * @author Marlon_Mendoza
 */
public class registrarProducto extends javax.swing.JPanel {

    /**
     * Creates new form registrarProducto
     */
    public registrarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        laboratorio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        principio_activo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre_producto = new javax.swing.JTextField();
        descripcion_producto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        codigo_digemid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lote = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ubicacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fecha_vencimiento = new javax.swing.JTextField();
        minimo_aviso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        unidad_blister = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        unidad_caja = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        precio_unitario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        precio_blister = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        precio_caja = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 226, 235));
        setPreferredSize(new java.awt.Dimension(1050, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(73, 148, 174));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(25, 46, 56));
        jLabel2.setText("AGREGAR PRODUCTOS AL ALMACEN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 840, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 46, 56));
        jLabel3.setText("Laboratorio:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 90, 30));

        laboratorio.setBackground(new java.awt.Color(255, 255, 255));
        laboratorio.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        laboratorio.setForeground(new java.awt.Color(0, 0, 0));
        laboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioActionPerformed(evt);
            }
        });
        add(laboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 250, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 46, 56));
        jLabel4.setText("Descripcion de producto:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 230, 30));

        principio_activo.setBackground(new java.awt.Color(255, 255, 255));
        principio_activo.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        principio_activo.setForeground(new java.awt.Color(0, 0, 0));
        principio_activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principio_activoActionPerformed(evt);
            }
        });
        add(principio_activo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 410, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 46, 56));
        jLabel5.setText("Principio activo:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 170, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(25, 46, 56));
        jLabel7.setText("Nombre del producto:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 140, 30));

        nombre_producto.setBackground(new java.awt.Color(255, 255, 255));
        nombre_producto.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        nombre_producto.setForeground(new java.awt.Color(0, 0, 0));
        nombre_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_productoActionPerformed(evt);
            }
        });
        add(nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 250, 35));

        descripcion_producto.setBackground(new java.awt.Color(255, 255, 255));
        descripcion_producto.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        descripcion_producto.setForeground(new java.awt.Color(0, 0, 0));
        descripcion_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcion_productoActionPerformed(evt);
            }
        });
        add(descripcion_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 410, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 46, 56));
        jLabel6.setText("Codigo Digemid:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 120, 30));

        codigo_digemid.setBackground(new java.awt.Color(255, 255, 255));
        codigo_digemid.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        codigo_digemid.setForeground(new java.awt.Color(0, 0, 0));
        codigo_digemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_digemidActionPerformed(evt);
            }
        });
        add(codigo_digemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 250, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(25, 46, 56));
        jLabel8.setText("Lote:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 120, 30));

        lote.setBackground(new java.awt.Color(255, 255, 255));
        lote.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lote.setForeground(new java.awt.Color(0, 0, 0));
        lote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loteActionPerformed(evt);
            }
        });
        add(lote, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 250, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(25, 46, 56));
        jLabel9.setText("Ubicacion:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 120, 30));

        ubicacion.setBackground(new java.awt.Color(255, 255, 255));
        ubicacion.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        ubicacion.setForeground(new java.awt.Color(0, 0, 0));
        ubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubicacionActionPerformed(evt);
            }
        });
        add(ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 250, 35));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(25, 46, 56));
        jLabel10.setText("Stock:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 140, 30));

        stock.setBackground(new java.awt.Color(255, 255, 255));
        stock.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        stock.setForeground(new java.awt.Color(0, 0, 0));
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 250, 35));

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(25, 46, 56));
        jLabel11.setText("Fecha de vencimiento:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 140, 30));

        fecha_vencimiento.setBackground(new java.awt.Color(255, 255, 255));
        fecha_vencimiento.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        fecha_vencimiento.setForeground(new java.awt.Color(0, 0, 0));
        fecha_vencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_vencimientoActionPerformed(evt);
            }
        });
        add(fecha_vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 250, 35));

        minimo_aviso.setBackground(new java.awt.Color(255, 255, 255));
        minimo_aviso.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        minimo_aviso.setForeground(new java.awt.Color(0, 0, 0));
        minimo_aviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimo_avisoActionPerformed(evt);
            }
        });
        add(minimo_aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 250, 35));

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(25, 46, 56));
        jLabel12.setText("Minimo para aviso:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 140, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(25, 46, 56));
        jLabel13.setText("Unidad x blister:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 140, 30));

        unidad_blister.setBackground(new java.awt.Color(255, 255, 255));
        unidad_blister.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        unidad_blister.setForeground(new java.awt.Color(0, 0, 0));
        unidad_blister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidad_blisterActionPerformed(evt);
            }
        });
        add(unidad_blister, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 250, 35));

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(25, 46, 56));
        jLabel14.setText("Unidad x caja:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 140, 30));

        unidad_caja.setBackground(new java.awt.Color(255, 255, 255));
        unidad_caja.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        unidad_caja.setForeground(new java.awt.Color(0, 0, 0));
        unidad_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidad_cajaActionPerformed(evt);
            }
        });
        add(unidad_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 250, 35));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(25, 46, 56));
        jLabel15.setText("Precio unitario");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 140, 30));

        precio_unitario.setBackground(new java.awt.Color(255, 255, 255));
        precio_unitario.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        precio_unitario.setForeground(new java.awt.Color(0, 0, 0));
        precio_unitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_unitarioActionPerformed(evt);
            }
        });
        add(precio_unitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 250, 35));

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(25, 46, 56));
        jLabel16.setText("Precio blister");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 140, 30));

        precio_blister.setBackground(new java.awt.Color(255, 255, 255));
        precio_blister.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        precio_blister.setForeground(new java.awt.Color(0, 0, 0));
        precio_blister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_blisterActionPerformed(evt);
            }
        });
        add(precio_blister, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 250, 35));

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(25, 46, 56));
        jLabel17.setText("Precio caja");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, 140, 30));

        precio_caja.setBackground(new java.awt.Color(255, 255, 255));
        precio_caja.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        precio_caja.setForeground(new java.awt.Color(0, 0, 0));
        precio_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_cajaActionPerformed(evt);
            }
        });
        add(precio_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, 250, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void laboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laboratorioActionPerformed

    private void principio_activoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principio_activoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_principio_activoActionPerformed

    private void nombre_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_productoActionPerformed

    private void descripcion_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcion_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcion_productoActionPerformed

    private void codigo_digemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_digemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_digemidActionPerformed

    private void loteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loteActionPerformed

    private void ubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacionActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    private void fecha_vencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_vencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_vencimientoActionPerformed

    private void minimo_avisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimo_avisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimo_avisoActionPerformed

    private void unidad_blisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidad_blisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidad_blisterActionPerformed

    private void unidad_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidad_cajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidad_cajaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            producto p = new producto(nombre_producto.getText(),laboratorio.getText(),descripcion_producto.getText(),principio_activo.getText(),codigo_digemid.getText(),lote.getText(),ubicacion.getText(),fecha_vencimiento.getText(),Integer.parseInt(stock.getText()),Integer.parseInt(minimo_aviso.getText()),Integer.parseInt(unidad_blister.getText()),Integer.parseInt(unidad_caja.getText()), Double.parseDouble(precio_unitario.getText()),Double.parseDouble(precio_blister.getText()),Double.parseDouble(precio_caja.getText()));
            System.out.println(nombre_producto.getText());
            DAOProductos dao = new DAOUserImpl();
            dao.registrar(p);
        } catch (Exception ex) {
            Logger.getLogger(registrarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void precio_unitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_unitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_unitarioActionPerformed

    private void precio_blisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_blisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_blisterActionPerformed

    private void precio_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_cajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_cajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo_digemid;
    private javax.swing.JTextField descripcion_producto;
    private javax.swing.JTextField fecha_vencimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField laboratorio;
    private javax.swing.JTextField lote;
    private javax.swing.JTextField minimo_aviso;
    private javax.swing.JTextField nombre_producto;
    private javax.swing.JTextField precio_blister;
    private javax.swing.JTextField precio_caja;
    private javax.swing.JTextField precio_unitario;
    private javax.swing.JTextField principio_activo;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField ubicacion;
    private javax.swing.JTextField unidad_blister;
    private javax.swing.JTextField unidad_caja;
    // End of variables declaration//GEN-END:variables
}
